/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;

import conexao.Conexao;
import dao.GerenciadorAbastecimento;
import dao.GerenciadorVeiculo;
import excecao.ExcecaoConexao;
import excecao.ExcecaoSQL;
import java.io.InputStream;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.Abastecimento;
import model.Veiculo;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import verificacao.Redimensionar;

/**
 *
 * @author aalano
 */
public class FrmTelaPrincipal extends javax.swing.JFrame {

    private Abastecimento obj = new Abastecimento();
    private GerenciadorAbastecimento gerenciador = new GerenciadorAbastecimento();
    private List<Veiculo> lista;

    /**
     * Creates new form FrmTelaPrincipal
     */
    public FrmTelaPrincipal() {
        setUndecorated(true);
        atualizarMes();
        initComponents();
        testarConexao();
        carregarID();
        try {
            carregarDadosVeiculoCombo();
        } catch (NullPointerException ex) {
            ex.printStackTrace();
        }

        ImageIcon icone = criarImageIcon("/icon/logo2.jpg", "");
        lbLogo.setIcon(icone);
        System.out.println(System.getProperties());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jDate = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        cbPlaca = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        tfMotorista = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        tfKmHs = new javax.swing.JTextField();
        tfLitros = new javax.swing.JTextField();
        tfCodigo = new javax.swing.JTextField();
        btPesquisar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        btSalvar = new javax.swing.JButton();
        btAtualizar = new javax.swing.JButton();
        btRemover = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        btFechar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lbLogo = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lbSaldoDisponivel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jmSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controle de Combustível");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setText("Data:");

        jDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jDateFocusGained(evt);
            }
        });

        jLabel2.setText("Placa:");

        cbPlaca.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbPlaca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbPlacaFocusGained(evt);
            }
        });

        jLabel3.setText("Motorista:");

        jLabel4.setText("Km / Hs:");

        jLabel5.setText("Litros:");

        jLabel6.setText("Código:");

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        tfKmHs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfKmHsKeyReleased(evt);
            }
        });

        tfLitros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfLitrosKeyReleased(evt);
            }
        });

        tfCodigo.setEditable(false);

        btPesquisar.setText("Pesquisar");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 179, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel7.setLayout(new java.awt.GridLayout(1, 0));

        btSalvar.setText("Salvar");
        btSalvar.setToolTipText("");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        jPanel7.add(btSalvar);

        btAtualizar.setText("Atualizar");
        btAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarActionPerformed(evt);
            }
        });
        jPanel7.add(btAtualizar);

        btRemover.setText("Remover");
        btRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverActionPerformed(evt);
            }
        });
        jPanel7.add(btRemover);

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });
        jPanel7.add(btCancelar);

        btFechar.setText("Fechar");
        btFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFecharActionPerformed(evt);
            }
        });
        jPanel7.add(btFechar);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbPlaca, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfMotorista)
                            .addComponent(tfKmHs)
                            .addComponent(tfLitros, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btPesquisar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(49, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPesquisar))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tfKmHs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tfLitros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(291, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Controle de Abastecimento");
        jLabel7.setToolTipText("");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(lbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lbLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Litros Disponíveis:");

        lbSaldoDisponivel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbSaldoDisponivel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSaldoDisponivel.setText("jLabel9");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbSaldoDisponivel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbSaldoDisponivel)
                .addContainerGap(227, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jMenuBar1.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/menu.png"))); // NOI18N
        jMenu1.setText("Menu");
        jMenu1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N

        jMenu3.setText("Gerenciamento");
        jMenu3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N

        jMenuItem9.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jMenuItem9.setText("Gerenciar Fornecedor");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem9);

        jMenuItem7.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jMenuItem7.setText("Gerenciar Proprietário");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuItem1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jMenuItem1.setText("Gerenciar Veículo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem8.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jMenuItem8.setText("Gerenciar Usuário");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);

        jMenu1.add(jMenu3);

        jMenuItem2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jMenuItem2.setText("Gerenciar Entrada de Combustível");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator2);

        jmSair.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jmSair.setText("Sair");
        jmSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmSairActionPerformed(evt);
            }
        });
        jMenu1.add(jmSair);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/relatorio.jpg"))); // NOI18N
        jMenu2.setText("Relatórios");
        jMenu2.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N

        jMenuItem3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jMenuItem3.setText("Relação de Abastecimentos");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);
        jMenu2.add(jSeparator1);

        jMenuItem4.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jMenuItem4.setText("Abastecimentos Proprietário");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jMenuItem5.setText("Data e Proprietário");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jMenuItem6.setText("Compra x Consumo");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);
        jMenuItem6.setVisible(false);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        DialogCadastroVeiculo cv = new DialogCadastroVeiculo(this, true);
        cv.setLocationRelativeTo(null);
        cv.setSize(Redimensionar.redimensionarTela());
        cv.setLocationRelativeTo(null);
        cv.dispose();
        cv.setUndecorated(true);
        cv.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        DialogEntradaCombustivel ec = new DialogEntradaCombustivel(this, true);
        ec.setLocationRelativeTo(null);
        ec.setSize(Redimensionar.redimensionarTela());
        ec.setLocationRelativeTo(null);
        ec.dispose();
        ec.setUndecorated(true);

        // set visible false oculta a tela principal ao abrir o 6 dialog
        ec.setVisible(true);

        //set visible true retorna a mostrar a tela principal apos fechar o ec
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        try {
            obj = this.getDados();
        } catch (NullPointerException | NumberFormatException ex) {
            JOptionPane.showMessageDialog(rootPane, "Campos em branco verifique!");
            return;
        }
        if (verificaAbastecimento(obj.getData(), obj.getVeiculo().getPlaca(), obj.getLitros()) == false) {
            try {
                gerenciador.inserir(obj);
                this.limparCampos();
            } catch (ExcecaoConexao ex) {
                JOptionPane.showMessageDialog(this, "Falha na conexão com o banco de dados.\n"
                        + "Msg.: " + ex.getMessage(), "Tela Principal", JOptionPane.ERROR_MESSAGE);
                Logger.getLogger(DialogCadastroVeiculo.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ExcecaoSQL ex) {
                JOptionPane.showMessageDialog(this, "Falha durante a gravação do registro.\n"
                        + "Msg.: " + ex.getMessage(), "Tela Principal", JOptionPane.ERROR_MESSAGE);
                Logger.getLogger(DialogCadastroVeiculo.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(rootPane, "Abastecimento realizado com sucesso!");
            btSalvar.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(null, "Abastecimento já cadastrado.");
        }
        btSalvar.setEnabled(true);
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed
        try {
            obj = this.getDados();
        } catch (NullPointerException | NumberFormatException ex) {
            ex.printStackTrace();
        }
        try {
            gerenciador.atualizar(obj);
            this.limparCampos();
        } catch (ExcecaoConexao ex) {
            JOptionPane.showMessageDialog(this, "Falha na conexão com o banco de dados.\n"
                    + "Msg.: " + ex.getMessage(), "Abastecimento", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(DialogCadastroVeiculo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ExcecaoSQL ex) {
            JOptionPane.showMessageDialog(this, "Falha durante a atualização dos dados no Banco de Dados.\n"
                    + "Msg.: " + ex.getMessage(), "Abstecimento", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(DialogCadastroVeiculo.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null, "Abastecimento atualizado com sucesso!");
    }//GEN-LAST:event_btAtualizarActionPerformed

    private void btRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverActionPerformed
        obj = this.getDados();
        try {
            if (JOptionPane.showConfirmDialog(this,
                    "Remover Abastecimento " + obj.getId(),
                    "Abastecimento", JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE) == 0) {
                gerenciador.remover(obj);
                this.limparCampos();
                JOptionPane.showMessageDialog(null, "Abastecimento removido com sucesso!");
            }
        } catch (ExcecaoConexao ex) {
            JOptionPane.showMessageDialog(this, "Falha na conexão com o banco de dados.\n"
                    + "Msg.: " + ex.getMessage(), "Abastecimento", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(DialogCadastroVeiculo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ExcecaoSQL ex) {
            JOptionPane.showMessageDialog(this, "Falha na remoção deste registro.\n"
                    + "Msg.: " + ex.getMessage(), "Abastecimento", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(DialogCadastroVeiculo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btRemoverActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        limparCampos();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFecharActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btFecharActionPerformed

    private void tfLitrosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfLitrosKeyReleased
        tfLitros.addKeyListener(new java.awt.event.KeyAdapter() {     // cria um listener ouvinte de digitação do fieldNumero  
            public void keyReleased(java.awt.event.KeyEvent evt) {  // cria um ouvinte para cada tecla pressionada  
                tfLitros.setText(tfLitros.getText().replaceAll("[^0-9]", "")); // faz com que pegue o texto a cada tecla digitada, e substituir tudo que não(^) seja numero  por ""  
            }
        });
    }//GEN-LAST:event_tfLitrosKeyReleased

    private void tfKmHsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfKmHsKeyReleased
        tfKmHs.addKeyListener(new java.awt.event.KeyAdapter() {     // cria um listener ouvinte de digitação do fieldNumero  
            public void keyReleased(java.awt.event.KeyEvent evt) {  // cria um ouvinte para cada tecla pressionada  
                tfKmHs.setText(tfKmHs.getText().replaceAll("[^0-9]", "")); // faz com que pegue o texto a cada tecla digitada, e substituir tudo que não(^) seja numero  por ""  
            }
        });
    }//GEN-LAST:event_tfKmHsKeyReleased

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        try {
            obj = gerenciador.obterAbastecimento(Integer.valueOf(JOptionPane.showInputDialog("Digite o código a ser pesquisado")));
        } catch (ExcecaoConexao ex) {
            JOptionPane.showMessageDialog(this, "Falha na conexão com o banco de dados.\n"
                    + "Msg.: " + ex.getMessage(), "Cadastro de Autor", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(DialogCadastroVeiculo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ExcecaoSQL ex) {
            JOptionPane.showMessageDialog(this, "Falha na pesquisa.\n"
                    + "Msg.: " + ex.getMessage(), "Cadastro de Autor", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(DialogCadastroVeiculo.class.getName()).log(Level.SEVERE, null, ex);
            return;
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(rootPane, "Digite um número para pesquisar.");
        }
        try {
            this.setDados(obj);
        } catch (NullPointerException ex) {
            return;
        }
        btSalvar.setEnabled(false);
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        estoqueLitros();
        
    }//GEN-LAST:event_formWindowActivated

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        DialogRelatorioAbastecimentos ra = new DialogRelatorioAbastecimentos(this, true);
        ra.setSize(Redimensionar.redimensionarTela());
        ra.setLocationRelativeTo(null);
        ra.dispose();
        ra.setUndecorated(true);
        ra.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jmSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jmSairActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        DialogRelatorioAbastecimentoProprietario rap = new DialogRelatorioAbastecimentoProprietario(this, true);
        rap.setLocationRelativeTo(null);
        rap.setSize(Redimensionar.redimensionarTela());
        rap.setLocationRelativeTo(null);
        rap.dispose();
        rap.setUndecorated(true);
        rap.setModal(false);
        rap.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        DialogRelatorioData rd = new DialogRelatorioData(this, true);
        //rd.dispose();
        //rd.setUndecorated(true);
        //rd.setModal(false);
        rd.setSize(Redimensionar.redimensionarTela());
        rd.setLocationRelativeTo(null);
        rd.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        DialogRelatorioCompraConsumo cc = new DialogRelatorioCompraConsumo(this, true);
        cc.setSize(Redimensionar.redimensionarTela());
        cc.setLocationRelativeTo(null);
        cc.dispose();
        cc.setUndecorated(true);
        cc.setModal(false);
        cc.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        DialogCadastroProprietario cp = new DialogCadastroProprietario(this, true);
        cp.setSize(Redimensionar.redimensionarTela());
        cp.setLocationRelativeTo(null);
        cp.dispose();
        cp.setUndecorated(true);
        cp.setModal(false);
        cp.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        DialogCadastroUsuario cad = new DialogCadastroUsuario(this, true);
        cad.setSize(Redimensionar.redimensionarTela());
        cad.setLocationRelativeTo(null);
        cad.dispose();
        cad.setUndecorated(true);
        cad.setModal(false);
        cad.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        DialogCadastroFornecedor cad = new DialogCadastroFornecedor(this, true);
        cad.setSize(Redimensionar.redimensionarTela());
        cad.setLocationRelativeTo(null);
        cad.dispose();
        cad.setUndecorated(true);
        cad.setModal(false);
        cad.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jDateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jDateFocusGained
        carregarDadosVeiculoCombo();
    }//GEN-LAST:event_jDateFocusGained

    private void cbPlacaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbPlacaFocusGained
        carregarDadosVeiculoCombo();
    }//GEN-LAST:event_cbPlacaFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FrmTelaPrincipal tp = new FrmTelaPrincipal();
        tp.setLocationRelativeTo(null);
        tp.setExtendedState(MAXIMIZED_BOTH);
        tp.setVisible(true);

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAtualizar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btFechar;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btRemover;
    private javax.swing.JButton btSalvar;
    private javax.swing.JComboBox cbPlaca;
    private com.toedter.calendar.JDateChooser jDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuItem jmSair;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JLabel lbSaldoDisponivel;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JTextField tfKmHs;
    private javax.swing.JTextField tfLitros;
    private javax.swing.JTextField tfMotorista;
    // End of variables declaration//GEN-END:variables

    private void limparCampos() {
        tfCodigo.setText(null);
        jDate.setDate(null);
        tfMotorista.setText(null);
        tfKmHs.setText(null);
        tfLitros.setText(null);
        cbPlaca.setSelectedIndex(-1);
        carregarID();
        btSalvar.setEnabled(true);
    }

    private Abastecimento getDados() {
        if (obj == null) {
            obj = new Abastecimento();
        }
        obj.setVeiculo((Veiculo) cbPlaca.getSelectedItem());
        obj.setData(jDate.getDate());
        if (obj.getVeiculo().getTipo().equals("CAMINHÃO") || obj.getVeiculo().getTipo().equals("UTILITÁRIO")) {
            obj.setKm(Integer.valueOf(tfKmHs.getText()));
            obj.setHoras(0);
        } else if (obj.getVeiculo().getTipo().equals("MÁQUINA")) {
            obj.setHoras(Integer.valueOf(tfKmHs.getText()));
            obj.setKm(0);
        }
        obj.setMotorista(tfMotorista.getText().toUpperCase());
        obj.setLitros(Float.valueOf(tfLitros.getText()));
        return obj;
    }

    private void setDados(Abastecimento obj) {
        this.jDate.setDate(obj.getData());
        this.tfKmHs.setText(String.valueOf(obj.getHoras()));
        this.tfKmHs.setText(String.valueOf(obj.getKm()));
        this.tfMotorista.setText(obj.getMotorista());
        this.tfLitros.setText(String.valueOf(obj.getLitros()));
        this.cbPlaca.setSelectedItem(obj.getVeiculo());
        this.tfCodigo.setText(String.valueOf(obj.getId()));
    }

    private boolean verificaAbastecimento(Date data, String placa, float litros) {
        try {
            if (gerenciador.ValorExistente(data, placa, litros) == false) {
                return false;
            }
        } catch (ExcecaoSQL | ExcecaoConexao | SQLException ex) {
            Logger.getLogger(DialogCadastroVeiculo.class.getName()).log(Level.SEVERE, null, ex);
        }
        return true;
    }

    public void carregarDadosVeiculoCombo() {
        GerenciadorVeiculo gv = new GerenciadorVeiculo();
        try {
            lista = gv.obterTodos();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Nenhum veículo cadastrado.");
        }
        cbPlaca.setModel(
                new DefaultComboBoxModel(lista.toArray()));
        cbPlaca.setSelectedIndex(-1);
    }

    public ImageIcon criarImageIcon(String caminho, String descricao) {
        java.net.URL imgURL = getClass().getResource(caminho);
        if (imgURL != null) {
            return new ImageIcon(imgURL, descricao);
        } else {
            System.err.println("Não foi possível carregar o arquivo de imagem: " + caminho);
            return null;
        }
    }

    public void estoqueLitros()  {
        float x = 0;
        try {
            x = gerenciador.getLitrosEntrada() - gerenciador.getLitrosSaida();
        } catch (ExcecaoConexao ex) {
            Logger.getLogger(FrmTelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(FrmTelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Conexão perdida o sistema será encerrado");
            System.exit(0);
        } catch (ExcecaoSQL ex) {
            Logger.getLogger(FrmTelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } 
        NumberFormat nb = new DecimalFormat("0.00");
        lbSaldoDisponivel.setText(String.valueOf(nb.format(x)));
    }

    public void carregarID() {
        try {
            tfCodigo.setText(String.valueOf(gerenciador.lastID()));
        } catch (SQLException ex) {
            Logger.getLogger(DialogCadastroVeiculo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ExcecaoConexao ex) {
            Logger.getLogger(DialogCadastroVeiculo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ExcecaoSQL ex) {
            Logger.getLogger(DialogCadastroVeiculo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void testarConexao() {
        try {
            conexao.Conexao.getConnection();
        } catch (ExcecaoConexao ex) {
            Logger.getLogger(FrmTelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ExcecaoSQL ex) {
            Logger.getLogger(FrmTelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Servidor não encontrado");
            System.exit(0);
        }
    }

    public void relatorio(InputStream is) {
        try {
            JasperPrint print = JasperFillManager.fillReport(is, null, conexao.Conexao.getConnection());
            JasperViewer viewer = new JasperViewer(print, false);
            viewer.setExtendedState(MAXIMIZED_BOTH);
            viewer.setVisible(true);
            viewer.setZoomRatio((float) 0.8);
        } catch (ExcecaoConexao | ExcecaoSQL ex) {
            Logger.getLogger(FrmTelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(FrmTelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassCastException ex) {
            Logger.getLogger(FrmTelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void atualizarMes() {
        PreparedStatement ps;
        try {
            ps = Conexao.getConnection().prepareStatement("UPDATE ABASTECIMENTO SET MES = MONTH(ABASTECIMENTO.DATA);");
            ps.executeUpdate();
        } catch (ExcecaoConexao ex) {
            Logger.getLogger(DialogRelatorioCompraConsumo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ExcecaoSQL ex) {
            Logger.getLogger(DialogRelatorioCompraConsumo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(DialogRelatorioCompraConsumo.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

}
